### ISSUE TITLE
Crashes don't send to AppCenter

### ISSUE THREAD

**Issue by druger** [microsoft/appcenter-sdk-android#1343]
### **Description**

After migration from HockeyApp Sdk crashes don't visible in console. In log we can see error with such code `ReasonCode: AppSecretDenied ` But my app secret is correct I checked it many times.

### **Details**

1. Which SDK version are you using?
    - 2.5.1
2. Which OS version did you experience the issue on?
    - Android 9.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Samsung Galaxy S8 physical device
4. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
```
2019-12-27 14:24:52.616 31270-31270/com.kg.gettransfer I/AppCenter: App Center SDK configured successfully.
2019-12-27 14:24:52.634 31270-31484/com.kg.gettransfer D/AppCenter: Loaded stored sessions: {}
2019-12-27 14:24:52.672 31270-31484/com.kg.gettransfer W/AppCenter: Unable to get installID from Shared Preferences
2019-12-27 14:24:52.700 31270-31486/com.kg.gettransfer D/AppCenter: Network 101 is available.
2019-12-27 14:24:52.701 31270-31486/com.kg.gettransfer D/AppCenter: Network has been connected.
2019-12-27 14:24:52.748 31270-31484/com.kg.gettransfer I/AppCenter: Changed maximum database size to 10485760 bytes.
2019-12-27 14:24:52.748 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(group_core)
2019-12-27 14:24:52.767 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:24:52.776 31270-31484/com.kg.gettransfer D/AppCenter: App Center initialized.
2019-12-27 14:24:57.298 31270-31270/com.kg.gettransfer D/AppCenter: Cannot read instrumentation variables in a non-test environment.
2019-12-27 14:24:58.655 31270-31270/com.kg.gettransfer D/AppCenter: Cannot read instrumentation variables in a non-test environment.
2019-12-27 14:24:59.914 31270-31484/com.kg.gettransfer D/AppCenter: removeGroup(groupErrors)
2019-12-27 14:24:59.915 31270-31484/com.kg.gettransfer D/AppCenter: removeGroup(groupErrors/one)
2019-12-27 14:24:59.927 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(groupErrors)
2019-12-27 14:24:59.957 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(groupErrors) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:24:59.957 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(groupErrors/one)
2019-12-27 14:24:59.963 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(groupErrors/one) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:24:59.974 31270-31484/com.kg.gettransfer I/AppCenter: Crashes service started from application.
2019-12-27 14:25:00.335 31270-31484/com.kg.gettransfer D/AppCenter: removeGroup(group_analytics)
2019-12-27 14:25:00.335 31270-31484/com.kg.gettransfer D/AppCenter: removeGroup(group_analytics/one)
2019-12-27 14:25:00.337 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(group_analytics)
2019-12-27 14:25:00.341 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:00.342 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(group_analytics/one)
2019-12-27 14:25:00.348 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics/one) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:00.348 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(group_analytics_critical)
2019-12-27 14:25:00.351 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics_critical) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:00.351 31270-31484/com.kg.gettransfer D/AppCenter: addGroup(group_analytics_critical/one)
2019-12-27 14:25:00.359 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics_critical/one) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:00.365 31270-31484/com.kg.gettransfer I/AppCenter: Analytics service started from application.
2019-12-27 14:25:00.722 31270-31484/com.kg.gettransfer D/AppCenter: Creating alias: appcenter.0.AES/CBC/PKCS7Padding/256
2019-12-27 14:25:00.899 31270-31484/com.kg.gettransfer D/AppCenter: Using appcenter.0.AES/CBC/PKCS7Padding/256
2019-12-27 14:25:00.918 31270-31484/com.kg.gettransfer D/AppCenter: Using appcenter.0.RSA/ECB/PKCS1Padding/2048
2019-12-27 14:25:01.019 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics/one) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.022 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.023 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(groupErrors) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.024 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics_critical/one) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.025 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(groupErrors/one) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.026 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.027 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics_critical) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:01.888 31270-31484/com.kg.gettransfer D/AppCenter: Storing a log to the Persistence database for log type startService with flags=1
2019-12-27 14:25:02.028 31270-31484/com.kg.gettransfer D/AppCenter: Stored a log to the Persistence database for log type startService with databaseId=1
2019-12-27 14:25:02.028 31270-31484/com.kg.gettransfer D/AppCenter: enqueue(group_core) pendingLogCount=1
2019-12-27 14:25:02.029 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_core) pendingLogCount=1 batchTimeInterval=3000
2019-12-27 14:25:02.030 31270-31484/com.kg.gettransfer D/AppCenterAnalytics: onActivityResumed
2019-12-27 14:25:02.039 31270-31484/com.kg.gettransfer D/AppCenter: Storing a log to the Persistence database for log type startSession with flags=1
2019-12-27 14:25:02.079 31270-31484/com.kg.gettransfer D/AppCenter: Stored a log to the Persistence database for log type startSession with databaseId=2
2019-12-27 14:25:02.079 31270-31484/com.kg.gettransfer D/AppCenter: enqueue(group_analytics) pendingLogCount=1
2019-12-27 14:25:02.081 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=1 batchTimeInterval=3000
2019-12-27 14:25:05.032 31270-31484/com.kg.gettransfer D/AppCenter: triggerIngestion(group_core) pendingLogCount=1
2019-12-27 14:25:05.033 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 1 logs from the Persistence database for group_core
2019-12-27 14:25:05.055 31270-31484/com.kg.gettransfer D/AppCenter: Returning 1 log(s) with an ID, 74c6224f-d023-4dde-b7a4-498bfa50b0f3
2019-12-27 14:25:05.055 31270-31484/com.kg.gettransfer D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2019-12-27 14:25:05.056 31270-31484/com.kg.gettransfer D/AppCenter: 	null / 1
2019-12-27 14:25:05.057 31270-31484/com.kg.gettransfer D/AppCenter: ingestLogs(group_core,74c6224f-d023-4dde-b7a4-498bfa50b0f3) pendingLogCount=0
2019-12-27 14:25:05.072 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:05.082 31270-31484/com.kg.gettransfer D/AppCenter: triggerIngestion(group_analytics) pendingLogCount=1
2019-12-27 14:25:05.083 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 1 logs from the Persistence database for group_analytics
2019-12-27 14:25:05.104 31270-31484/com.kg.gettransfer D/AppCenter: Returning 1 log(s) with an ID, 10b1ba24-cb4b-462c-822c-7ccb5708e00f
2019-12-27 14:25:05.104 31270-31484/com.kg.gettransfer D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2019-12-27 14:25:05.104 31270-31484/com.kg.gettransfer D/AppCenter: 	1cccd7de-7409-4cd9-9faf-2869f7da2370 / 2
2019-12-27 14:25:05.116 31270-31484/com.kg.gettransfer D/AppCenter: ingestLogs(group_analytics,10b1ba24-cb4b-462c-822c-7ccb5708e00f) pendingLogCount=0
2019-12-27 14:25:05.125 31270-31484/com.kg.gettransfer D/AppCenterAnalytics: onActivityPaused
2019-12-27 14:25:05.134 31270-31484/com.kg.gettransfer D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2019-12-27 14:25:05.149 31270-31445/com.kg.gettransfer V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2019-12-27 14:25:05.150 31270-31445/com.kg.gettransfer V/AppCenter: Headers: {Install-ID=b020dd55-4c1f-4e01-9397-699427a8901c, App-Secret=****************************1d30df48, Content-Type=application/json}
2019-12-27 14:25:05.160 31270-31557/com.kg.gettransfer V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2019-12-27 14:25:05.162 31270-31557/com.kg.gettransfer V/AppCenter: Headers: {Install-ID=b020dd55-4c1f-4e01-9397-699427a8901c, App-Secret=****************************1d30df48, Content-Type=application/json}
2019-12-27 14:25:05.166 31270-31445/com.kg.gettransfer V/AppCenter: {
      "logs": [
        {
          "type": "startService",
          "timestamp": "2019-12-27T11:25:01.888Z",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "2.5.1",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "10",
            "osBuild": "QSR1.190920.001",
            "osApiLevel": 29,
            "locale": "en_US",
            "timeZoneOffset": 180,
            "screenSize": "1080x2028",
            "appVersion": "3.0",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "1",
            "appNamespace": "com.kg.gettransfer"
          },
          "services": [
            "Crashes",
            "Analytics"
          ]
        }
      ]
    }
2019-12-27 14:25:05.175 31270-31557/com.kg.gettransfer V/AppCenter: {
      "logs": [
        {
          "type": "startSession",
          "timestamp": "2019-12-27T11:25:02.038Z",
          "sid": "1cccd7de-7409-4cd9-9faf-2869f7da2370",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "2.5.1",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "10",
            "osBuild": "QSR1.190920.001",
            "osApiLevel": 29,
            "locale": "en_US",
            "timeZoneOffset": 180,
            "screenSize": "1080x2028",
            "appVersion": "3.0",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "1",
            "appNamespace": "com.kg.gettransfer"
          }
        }
      ]
    }
2019-12-27 14:25:05.906 31270-31445/com.kg.gettransfer V/AppCenter: HTTP response status=401 payload=CorrelationId: a1c2e152-4b06-4f0b-abae-c5262c834e16  ReasonCode: AppSecretDenied 
2019-12-27 14:25:07.055 31270-31557/com.kg.gettransfer V/AppCenter: HTTP response status=401 payload=CorrelationId: d53777e5-c8bf-4a7a-b1ea-bc3a7bbd6cc5  ReasonCode: AppSecretDenied 
2019-12-27 14:25:08.796 31270-31484/com.kg.gettransfer D/AppCenterAnalytics: onActivityResumed
2019-12-27 14:25:08.797 31270-31484/com.kg.gettransfer D/AppCenterAnalytics: noLogSentForLong=false wasBackgroundForLong=false
2019-12-27 14:25:08.901 31270-31484/com.kg.gettransfer E/AppCenter: Sending logs groupName=group_core id=74c6224f-d023-4dde-b7a4-498bfa50b0f3 failed
    com.microsoft.appcenter.http.HttpException: 401 - CorrelationId: a1c2e152-4b06-4f0b-abae-c5262c834e16  ReasonCode: AppSecretDenied 
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:265)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:49)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2019-12-27 14:25:08.901 31270-31484/com.kg.gettransfer D/AppCenter: Cancelling 1 network call(s).
2019-12-27 14:25:08.902 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics_critical
2019-12-27 14:25:08.912 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.912 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for group_analytics_critical
2019-12-27 14:25:08.920 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:08.921 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics_critical/one
2019-12-27 14:25:08.928 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.928 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for group_analytics_critical/one
2019-12-27 14:25:08.932 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:08.932 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for group_core
2019-12-27 14:25:08.936 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.937 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for group_core
2019-12-27 14:25:08.946 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:08.947 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics
2019-12-27 14:25:08.952 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.952 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for group_analytics
2019-12-27 14:25:08.954 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:08.954 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics/one
2019-12-27 14:25:08.958 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.958 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for group_analytics/one
2019-12-27 14:25:08.961 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:08.961 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for groupErrors
2019-12-27 14:25:08.976 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.976 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for groupErrors
2019-12-27 14:25:08.979 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:08.980 31270-31484/com.kg.gettransfer D/AppCenter: Trying to get 100 logs from the Persistence database for groupErrors/one
2019-12-27 14:25:08.984 31270-31484/com.kg.gettransfer D/AppCenter: No logs found in the Persistence database at the moment
2019-12-27 14:25:08.984 31270-31484/com.kg.gettransfer D/AppCenter: Deleting all logs from the Persistence database for groupErrors/one
2019-12-27 14:25:08.986 31270-31484/com.kg.gettransfer D/AppCenter: Deleted 0 logs.
2019-12-27 14:25:39.070 31270-31270/com.kg.gettransfer D/AppCenterCrashes: The memory running level (5) was saved.
```

**Comment by MatkovIvan** [comment]
Hi @druger,

Thanks for getting in touch!
`401/AppSecretDenied` is returned when something goes wrong with the app-secret value. But since you have checked the app secret and you are sure that it's correct, I suggest you to open an intercom support ticket (blue chat button on the portal) where you can share the details (like ids), so the support team can check your application.
I'm going to close this issue now, since we are using this issue tracker on GitHub only for client SDK bugs. If you think that this is the problem with this SDK - feel free to reopen it.
