### ISSUE TITLE
I got a "Sending logs groupName=group_core id=xxx failed"

### ISSUE THREAD

**Issue by hjthjthjt** [microsoft/appcenter-sdk-android#1388]
### **Description**

I got:
`2020-03-28 00:36:59.888 29736-29806/com.jakting.opengapps E/AppCenter: Sending logs groupName=group_analytics id=c2676fd6-342b-42c2-8914-0aeaa86ae3de failed
    javax.net.ssl.SSLHandshakeException: Connection closed by peer`

But I think my network is fine. Although I was in China, I used the available proxy during the test to ensure that it was in conjunction with

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. I add AppCenter SDK correctly. I can see users at appcenter.ms
![image](https://user-images.githubusercontent.com/3889846/77779070-e51f7d80-708c-11ea-93f7-e2b80ca7f776.png)

2. It just happens I did not why.

### **Details**

1. Which SDK version are you using?
    - 3.1.0
2. Which OS version did you experience the issue on?
    - Android 10
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -  OnePlus 7T Pro(HD1910) with Oxygen OS
4. What third party libraries are you using?
    - gson, okhttp4, tonyodev/fetch2
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

```
2020-03-28 00:36:53.520 29736-29736/com.jakting.opengapps I/AppCenter: App Center SDK configured successfully.
2020-03-28 00:36:53.524 29736-29736/com.jakting.opengapps D/AppCenter: Cannot read instrumentation variables in a non-test environment.
2020-03-28 00:36:53.528 29736-29736/com.jakting.opengapps D/AppCenter: Cannot read instrumentation variables in a non-test environment.
2020-03-28 00:36:53.549 29736-29806/com.jakting.opengapps D/AppCenter: Loaded stored sessions: {1585326468297=1585326468297//1585326468295, 1585326468337=1585326468337/af378f39-277d-4b31-a14d-0b2c308db1c0/1585326468295, 1585326482713=1585326482713//1585326482709, 1585326482752=1585326482752/f359f808-dac2-4cf5-8c88-9a70eaf03097/1585326482709, 1585326602099=1585326602099//1585326602096, 1585326602138=1585326602138/b5124d57-c211-46c2-a55d-d06b7477dfaa/1585326602096, 1585326630001=1585326630001//1585326629999, 1585326630044=1585326630044/cf8d222b-4f54-4093-9d43-749eafe2762c/1585326629999, 1585326655294=1585326655294//1585326655291, 1585326655344=1585326655344/8175ae68-2cfc-4d26-9f7a-77a43698d908/1585326655291}
2020-03-28 00:36:53.575 29736-29809/com.jakting.opengapps D/AppCenter: Network 139 is available.
2020-03-28 00:36:53.575 29736-29809/com.jakting.opengapps D/AppCenter: Network has been connected.
2020-03-28 00:36:53.589 29736-29806/com.jakting.opengapps I/AppCenter: Changed maximum database size to 10485760 bytes.
2020-03-28 00:36:53.589 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(group_core)
2020-03-28 00:36:53.592 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.594 29736-29806/com.jakting.opengapps D/AppCenter: App Center initialized.
2020-03-28 00:36:53.595 29736-29806/com.jakting.opengapps D/AppCenter: removeGroup(group_analytics)
2020-03-28 00:36:53.595 29736-29806/com.jakting.opengapps D/AppCenter: removeGroup(group_analytics/one)
2020-03-28 00:36:53.595 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(group_analytics)
2020-03-28 00:36:53.597 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.597 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(group_analytics/one)
2020-03-28 00:36:53.598 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_analytics/one) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.598 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(group_analytics_critical)
2020-03-28 00:36:53.599 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_analytics_critical) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.599 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(group_analytics_critical/one)
2020-03-28 00:36:53.600 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_analytics_critical/one) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.602 29736-29806/com.jakting.opengapps I/AppCenter: Analytics service started from application.
2020-03-28 00:36:53.602 29736-29806/com.jakting.opengapps D/AppCenter: removeGroup(groupErrors)
2020-03-28 00:36:53.602 29736-29806/com.jakting.opengapps D/AppCenter: removeGroup(groupErrors/one)
2020-03-28 00:36:53.602 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(groupErrors)
2020-03-28 00:36:53.603 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(groupErrors) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.603 29736-29806/com.jakting.opengapps D/AppCenter: addGroup(groupErrors/one)
2020-03-28 00:36:53.605 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(groupErrors/one) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:53.607 29736-29806/com.jakting.opengapps D/AppCenterCrashes: No previous minidump sub-folders.
2020-03-28 00:36:53.608 29736-29806/com.jakting.opengapps I/AppCenter: Crashes service started from application.
2020-03-28 00:36:53.614 29736-29806/com.jakting.opengapps D/AppCenter: Storing a log to the Persistence database for log type startService with flags=1
2020-03-28 00:36:53.626 29736-29806/com.jakting.opengapps D/AppCenter: Stored a log to the Persistence database for log type startService with databaseId=46
2020-03-28 00:36:53.626 29736-29806/com.jakting.opengapps D/AppCenter: enqueue(group_core) pendingLogCount=1
2020-03-28 00:36:53.626 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_core) pendingLogCount=1 batchTimeInterval=3000
2020-03-28 00:36:53.626 29736-29806/com.jakting.opengapps D/AppCenterAnalytics: onActivityResumed
2020-03-28 00:36:53.627 29736-29806/com.jakting.opengapps D/AppCenter: Storing a log to the Persistence database for log type startSession with flags=1
2020-03-28 00:36:53.635 29736-29806/com.jakting.opengapps D/AppCenter: Stored a log to the Persistence database for log type startSession with databaseId=47
2020-03-28 00:36:53.635 29736-29806/com.jakting.opengapps D/AppCenter: enqueue(group_analytics) pendingLogCount=1
2020-03-28 00:36:53.635 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=1 batchTimeInterval=3000
2020-03-28 00:36:56.639 29736-29806/com.jakting.opengapps D/AppCenter: triggerIngestion(group_core) pendingLogCount=1
2020-03-28 00:36:56.639 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 1 logs from the Persistence database for group_core
2020-03-28 00:36:56.643 29736-29806/com.jakting.opengapps D/AppCenter: Returning 1 log(s) with an ID, a5355ed6-94ce-49b9-a04e-f91ba26d0994
2020-03-28 00:36:56.643 29736-29806/com.jakting.opengapps D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2020-03-28 00:36:56.643 29736-29806/com.jakting.opengapps D/AppCenter: 	null / 46
2020-03-28 00:36:56.643 29736-29806/com.jakting.opengapps D/AppCenter: ingestLogs(group_core,a5355ed6-94ce-49b9-a04e-f91ba26d0994) pendingLogCount=0
2020-03-28 00:36:56.643 29736-29806/com.jakting.opengapps D/AppCenter: triggerIngestion(group_analytics) pendingLogCount=1
2020-03-28 00:36:56.643 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 1 logs from the Persistence database for group_analytics
2020-03-28 00:36:56.645 29736-29806/com.jakting.opengapps D/AppCenter: Returning 1 log(s) with an ID, c2676fd6-342b-42c2-8914-0aeaa86ae3de
2020-03-28 00:36:56.645 29736-29806/com.jakting.opengapps D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2020-03-28 00:36:56.645 29736-29806/com.jakting.opengapps D/AppCenter: 	a77d3cab-5b54-4144-85a5-581090610277 / 47
2020-03-28 00:36:56.645 29736-29806/com.jakting.opengapps D/AppCenter: ingestLogs(group_analytics,c2676fd6-342b-42c2-8914-0aeaa86ae3de) pendingLogCount=0
2020-03-28 00:36:56.666 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:56.667 29736-29806/com.jakting.opengapps D/AppCenter: checkPendingLogs(group_analytics) pendingLogCount=0 batchTimeInterval=3000
2020-03-28 00:36:56.675 29736-29811/com.jakting.opengapps V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2020-03-28 00:36:56.675 29736-29811/com.jakting.opengapps V/AppCenter: Headers: {Install-ID=35afb18a-2e40-483c-8873-21ca40e61860, App-Secret=****************************e97c6c53, Content-Type=application/json}
2020-03-28 00:36:56.676 29736-29811/com.jakting.opengapps V/AppCenter: {
      "logs": [
        {
          "type": "startSession",
          "timestamp": "2020-03-27T16:36:53.627Z",
          "sid": "a77d3cab-5b54-4144-85a5-581090610277",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "3.1.0",
            "model": "HD1910",
            "oemName": "OnePlus",
            "osName": "Android",
            "osVersion": "10",
            "osBuild": "QKQ1.190716.003",
            "osApiLevel": 29,
            "locale": "zh_CN_#Hans",
            "timeZoneOffset": 480,
            "screenSize": "1440x3064",
            "appVersion": "3.0.1.1",
            "carrierName": "CHN-CT",
            "carrierCountry": "cn",
            "appBuild": "20200327",
            "appNamespace": "com.jakting.opengapps"
          }
        }
      ]
    }
2020-03-28 00:36:56.678 29736-29813/com.jakting.opengapps V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2020-03-28 00:36:56.678 29736-29813/com.jakting.opengapps V/AppCenter: Headers: {Install-ID=35afb18a-2e40-483c-8873-21ca40e61860, App-Secret=****************************e97c6c53, Content-Type=application/json}
2020-03-28 00:36:56.681 29736-29813/com.jakting.opengapps V/AppCenter: {
      "logs": [
        {
          "type": "startService",
          "timestamp": "2020-03-27T16:36:53.613Z",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "3.1.0",
            "model": "HD1910",
            "oemName": "OnePlus",
            "osName": "Android",
            "osVersion": "10",
            "osBuild": "QKQ1.190716.003",
            "osApiLevel": 29,
            "locale": "zh_CN_#Hans",
            "timeZoneOffset": 480,
            "screenSize": "1440x3064",
            "appVersion": "3.0.1.1",
            "carrierName": "CHN-CT",
            "carrierCountry": "cn",
            "appBuild": "20200327",
            "appNamespace": "com.jakting.opengapps"
          },
          "services": [
            "Analytics",
            "Crashes"
          ]
        }
      ]
    }
2020-03-28 00:36:59.888 29736-29806/com.jakting.opengapps E/AppCenter: Sending logs groupName=group_analytics id=c2676fd6-342b-42c2-8914-0aeaa86ae3de failed
    javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
        at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-03-28 00:36:59.888 29736-29806/com.jakting.opengapps D/AppCenter: Cancelling 1 network call(s).
2020-03-28 00:36:59.889 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics_critical
2020-03-28 00:36:59.892 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.892 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for group_analytics_critical
2020-03-28 00:36:59.893 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 0 logs.
2020-03-28 00:36:59.893 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics_critical/one
2020-03-28 00:36:59.895 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.895 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for group_analytics_critical/one
2020-03-28 00:36:59.895 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 0 logs.
2020-03-28 00:36:59.896 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for group_core
2020-03-28 00:36:59.897 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.897 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for group_core
2020-03-28 00:36:59.922 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 1 logs.
2020-03-28 00:36:59.922 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics
2020-03-28 00:36:59.924 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.924 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for group_analytics
2020-03-28 00:36:59.929 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 1 logs.
2020-03-28 00:36:59.929 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for group_analytics/one
2020-03-28 00:36:59.930 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.930 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for group_analytics/one
2020-03-28 00:36:59.931 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 0 logs.
2020-03-28 00:36:59.931 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for groupErrors
2020-03-28 00:36:59.932 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.932 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for groupErrors
2020-03-28 00:36:59.932 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 0 logs.
2020-03-28 00:36:59.932 29736-29806/com.jakting.opengapps D/AppCenter: Trying to get 100 logs from the Persistence database for groupErrors/one
2020-03-28 00:36:59.933 29736-29806/com.jakting.opengapps D/AppCenter: No logs found in the Persistence database at the moment
2020-03-28 00:36:59.933 29736-29806/com.jakting.opengapps D/AppCenter: Deleting all logs from the Persistence database for groupErrors/one
2020-03-28 00:36:59.933 29736-29806/com.jakting.opengapps D/AppCenter: Deleted 0 logs.
2020-03-28 00:37:00.702 29736-29813/com.jakting.opengapps V/AppCenter: HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"45f256a1-a87a-4833-a80c-0288dd8f1493"}
```

**Comment by russelarms** [comment]
Hi, thanks for reaching out!
It seems like a temporal network issue since another request was successful:
```
HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"45f256a1-a87a-4833-a80c-0288dd8f1493"}
```
Do you still experience this problem?

**Comment by russelarms** [comment]
We haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.
