### ISSUE TITLE
There is no crash in dashboard

### ISSUE THREAD

**Issue by MK-9** [microsoft/appcenter-sdk-android#1482]
### **Description**
I can send log to https://in.appcenter.ms/logs?api-version=1.0.0, but I cannot see anything in diagnostic in dashborad.
### **Repro Steps**
Please list the steps used to reproduce your issue.
1.Crashes.setListener(crashesListener)
2.Crashes.setEnabled(true);
3.AppCenter.setLogLevel(Log.VERBOSE);
4.AppCenter.start(getApplication(), "app_secret", Crashes.class);
5.AppCenter.setUserId("112233");
### **Details**
1. Which SDK version are you using?
    -3.3.1
2. Which OS version did you experience the issue on?
    - Android 8.0.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Xiaomi MI 5s
4. What third party libraries are you using?
    - retrofit 1.9 , glide
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
2020-12-07 10:53:14.165 10671-10671/ir.mservices.mybook D/AppCenterCrashes: Saving uncaught exception.
2020-12-07 10:53:14.207 10671-10671/ir.mservices.mybook D/AppCenterCrashes: Saved JSON content for ingestion into /data/user/0/ir.mservices.mybook/files/error/81b12061-e632-4ed2-a321-e54aa54e806c.json
2020-12-07 10:53:14.209 10671-10671/ir.mservices.mybook D/AppCenterCrashes: Saved stack trace as is for client side inspection in /data/user/0/ir.mservices.mybook/files/error/81b12061-e632-4ed2-a321-e54aa54e806c.throwable stack trace:com.microsoft.appcenter.crashes.model.TestCrashException: Test crash exception generated by SDK
        at com.microsoft.appcenter.crashes.Crashes.generateTestCrash(Crashes.java:287)
        at ir.mservices.mybook.fragments.StoreSearchFragment.onResume(StoreSearchFragment.java:293)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3011)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:614)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:314)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:512)
        at androidx.fragment.app.DefaultSpecialEffectsController.removeCancellationSignal(DefaultSpecialEffectsController.java:81)
        at androidx.fragment.app.DefaultSpecialEffectsController.startAnimation(DefaultSpecialEffectsController.java:216)
        at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:187)
        at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:231)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2187)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2083)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1985)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:600)
        at ir.mservices.mybook.base.FragmentStackManager.callIndexChangeListener(FragmentStackManager.java:281)
        at ir.mservices.mybook.base.FragmentStackManager.setCurrentTab(FragmentStackManager.java:232)
        at ir.mservices.mybook.base.MservicesActivity.onTabButtonClicked(MservicesActivity.java:284)
        at ir.mservices.mybook.core.MainActivity.lambda$new$0$MainActivity(MainActivity.java:472)
        at ir.mservices.mybook.core.-$$Lambda$MainActivity$o-miJ8zwbECMaYitUCL9ZX0hrrM.onNavigationItemSelected(Unknown Source:2)
        at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:242)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:123)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2020-12-07 10:53:14.210 10671-10878/ir.mservices.mybook D/AppCenter: Cleared pending log states
2020-12-07 10:53:14.211 10671-10878/ir.mservices.mybook D/AppCenter: Channel completed shutdown.
2020-12-07 10:53:24.647 11133-11133/ir.mservices.mybook I/AppCenter: App Center SDK configured successfully.
2020-12-07 10:53:24.657 11133-11133/ir.mservices.mybook D/AppCenter: Cannot read instrumentation variables in a non-test environment.
2020-12-07 10:53:24.661 11133-11295/ir.mservices.mybook D/AppCenter: Loaded stored sessions: {1607284416079=1607284416079//1607284416074, 1607284606079=1607284606079//1607284606049, 1607284754320=1607284754320//1607284754316, 1607284779990=1607284779990//1607284779961, 1607295629204=1607295629204//1607295629170, 1607306389857=1607306389857//1607306389835, 1607318259442=1607318259442//1607318259433, 1607324810776=1607324810776//1607324810767, 1607324904130=1607324904130//1607324904124, 1607325746898=1607325746898//1607325746885}
2020-12-07 10:53:24.667 11133-11214/ir.mservices.mybook D/AppCenter: Network 114 is available.
2020-12-07 10:53:24.667 11133-11214/ir.mservices.mybook D/AppCenter: Network has been connected.
2020-12-07 10:53:24.688 11133-11295/ir.mservices.mybook I/AppCenter: Changed maximum database size to 10485760 bytes.
2020-12-07 10:53:24.688 11133-11295/ir.mservices.mybook D/AppCenter: addGroup(group_core)
2020-12-07 10:53:24.690 11133-11295/ir.mservices.mybook D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2020-12-07 10:53:24.691 11133-11295/ir.mservices.mybook D/AppCenter: App Center initialized.
2020-12-07 10:53:24.692 11133-11295/ir.mservices.mybook D/AppCenter: removeGroup(groupErrors)
2020-12-07 10:53:24.692 11133-11295/ir.mservices.mybook D/AppCenter: removeGroup(groupErrors/one)
2020-12-07 10:53:24.693 11133-11295/ir.mservices.mybook D/AppCenter: addGroup(groupErrors)
2020-12-07 10:53:24.695 11133-11295/ir.mservices.mybook D/AppCenter: checkPendingLogs(groupErrors) pendingLogCount=0 batchTimeInterval=3000
2020-12-07 10:53:24.695 11133-11295/ir.mservices.mybook D/AppCenter: addGroup(groupErrors/one)
2020-12-07 10:53:24.699 11133-11295/ir.mservices.mybook D/AppCenter: checkPendingLogs(groupErrors/one) pendingLogCount=0 batchTimeInterval=3000
2020-12-07 10:53:24.701 11133-11295/ir.mservices.mybook D/AppCenterCrashes: Processing crash report for the last session.
2020-12-07 10:53:24.930 11133-11295/ir.mservices.mybook D/AppCenterCrashes: Processed crash report for the last session.
2020-12-07 10:53:24.930 11133-11295/ir.mservices.mybook D/AppCenterCrashes: No previous minidump sub-folders.
2020-12-07 10:53:24.931 11133-11295/ir.mservices.mybook D/AppCenterCrashes: Process pending error file: /data/user/0/ir.mservices.mybook/files/error/81b12061-e632-4ed2-a321-e54aa54e806c.json
2020-12-07 10:53:25.060 11133-11295/ir.mservices.mybook D/AppCenterCrashes: CrashesListener.shouldProcess returned false, clean up and ignore log: 81b12061-e632-4ed2-a321-e54aa54e806c
2020-12-07 10:53:25.061 11133-11295/ir.mservices.mybook I/AppCenterCrashes: Deleting error log file 81b12061-e632-4ed2-a321-e54aa54e806c.json
2020-12-07 10:53:25.062 11133-11295/ir.mservices.mybook I/AppCenterCrashes: Deleting throwable file 81b12061-e632-4ed2-a321-e54aa54e806c.throwable
2020-12-07 10:53:25.063 11133-11295/ir.mservices.mybook I/AppCenter: Crashes service started from application.
2020-12-07 10:53:25.060 11133-11295/ir.mservices.mybook D/AppCenterCrashes: CrashesListener.shouldProcess returned false, clean up and ignore log: 81b12061-e632-4ed2-a321-e54aa54e806c
2020-12-07 10:53:25.061 11133-11295/ir.mservices.mybook I/AppCenterCrashes: Deleting error log file 81b12061-e632-4ed2-a321-e54aa54e806c.json
2020-12-07 10:53:25.062 11133-11295/ir.mservices.mybook I/AppCenterCrashes: Deleting throwable file 81b12061-e632-4ed2-a321-e54aa54e806c.throwable
2020-12-07 10:53:25.063 11133-11295/ir.mservices.mybook I/AppCenter: Crashes service started from application.
2020-12-07 10:53:25.077 11133-11295/ir.mservices.mybook D/AppCenter: Storing a log to the Persistence database for log type startService with flags=1
2020-12-07 10:53:25.093 11133-11295/ir.mservices.mybook D/AppCenter: Stored a log to the Persistence database for log type startService with databaseId=42
2020-12-07 10:53:25.093 11133-11295/ir.mservices.mybook D/AppCenter: enqueue(group_core) pendingLogCount=1
2020-12-07 10:53:25.094 11133-11295/ir.mservices.mybook D/AppCenter: checkPendingLogs(group_core) pendingLogCount=1 batchTimeInterval=3000
2020-12-07 10:53:28.097 11133-11295/ir.mservices.mybook D/AppCenter: triggerIngestion(group_core) pendingLogCount=1
2020-12-07 10:53:28.097 11133-11295/ir.mservices.mybook D/AppCenter: Trying to get 1 logs from the Persistence database for group_core
2020-12-07 10:53:28.114 11133-11295/ir.mservices.mybook D/AppCenter: Returning 1 log(s) with an ID, 39a93e58-4591-459a-bac8-f13506e4b615
2020-12-07 10:53:28.115 11133-11295/ir.mservices.mybook D/AppCenter: The SID/ID pairs for returning log(s) is/are:
2020-12-07 10:53:28.115 11133-11295/ir.mservices.mybook D/AppCenter: 	null / 42
2020-12-07 10:53:28.116 11133-11295/ir.mservices.mybook D/AppCenter: ingestLogs(group_core,39a93e58-4591-459a-bac8-f13506e4b615) pendingLogCount=0
2020-12-07 10:53:28.124 11133-11295/ir.mservices.mybook D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
2020-12-07 10:53:28.134 11133-11200/ir.mservices.mybook V/AppCenter: Calling https://in.appcenter.ms/logs?api-version=1.0.0...
2020-12-07 10:53:28.134 11133-11200/ir.mservices.mybook V/AppCenter: Headers: {Install-ID=95986ae5-c0a3-4721-9c14-f259ff844ba6, App-Secret=****************************9d6ad93a, Content-Type=application/json}
2020-12-07 10:53:28.136 11133-11200/ir.mservices.mybook V/AppCenter: {
      "logs": [
        {
          "type": "startService",
          "timestamp": "2020-12-07T07:23:25.077Z",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "3.3.1",
            "model": "MI 5s",
            "oemName": "Xiaomi",
            "osName": "Android",
            "osVersion": "8.0.0",
            "osBuild": "OPR1.170623.032",
            "osApiLevel": 26,
            "locale": "en_US",
            "timeZoneOffset": 210,
            "screenSize": "1080x1920",
            "appVersion": "8.3.4d",
            "appBuild": "834",
            "appNamespace": "ir.mservices.mybook"
          },
          "services": [
            "Crashes"
          ]
        }
      ]
    }
2020-12-07 10:53:30.952 11133-11200/ir.mservices.mybook V/AppCenter: HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"6f7f630c-0776-4f7b-bc7b-3409ea1a2089"}
2020-12-07 10:53:30.963 11133-11295/ir.mservices.mybook D/AppCenter: Deleting logs from the Persistence database for group_core with 39a93e58-4591-459a-bac8-f13506e4b615
2020-12-07 10:53:30.964 11133-11295/ir.mservices.mybook D/AppCenter: The IDs for deleting log(s) is/are:
2020-12-07 10:53:30.964 11133-11295/ir.mservices.mybook D/AppCenter: 	42
2020-12-07 10:53:30.997 11133-11295/ir.mservices.mybook D/AppCenter: checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000

**Comment by olmisa** [comment]
Hello @MK-9 ,
thanks for using App Center. I don't understand from the repro steps at which moment the crash was done and at which moment we can't see it on a dashboard. Also why you try to enable the crash module before the start?
Is it possible to attach the demo project with reproduction (without app secret)? 
Thanks

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
