### ISSUE TITLE
App ANR due to deadlock in appcenter SDK

### ISSUE THREAD

**Issue by yulin-li** [microsoft/appcenter-sdk-android#1486]
### **Description**

App ANR due to deadlock in appcenter SDK

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
    - 3.2.1
2. Which OS version did you experience the issue on?
    - Android 8.0 (api level 26)
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - A customized armv8 device
4. What third party libraries are you using?
    - no
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
    - didn't get the log with verbose log level.

Log

suspend all histogram:	Sum: 8.435ms 99% C.I. 2us-3943us Avg: 766.818us Max: 3943us
DALVIK THREADS (25):
"AppCenter.Looper" daemon prio=5 tid=22 Runnable
  | group="main" sCount=0 dsCount=0 flags=0 obj=0x12fc09f8 self=0x7472891600
  | sysTid=2879 nice=0 cgrp=default sched=0/0 handle=0x74722d74f0
  | state=R schedstat=( 125712756 151271047 149 ) utm=11 stm=1 core=0 HZ=100
  | stack=0x74721d5000-0x74721d7000 stackSize=1037KB
  | held mutexes= "mutator lock"(shared held)
  at android.icu.impl.CacheValue.futureInstancesWillBeStrong(CacheValue.java:66)
  at android.icu.impl.SoftCache.getInstance(SoftCache.java:72)
  at android.icu.util.ULocale.forLocale(ULocale.java:418)
  at android.icu.util.Currency.getInstance(Currency.java:150)
  at java.util.Currency.getInstance(Currency.java:130)
  at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:679)
  at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:105)
  at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:159)
  at java.text.NumberFormat.getInstance(NumberFormat.java:838)
  at java.text.NumberFormat.getIntegerInstance(NumberFormat.java:495)
  at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:689)
  at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:623)
  at com.microsoft.appcenter.ingestion.models.json.JSONDateUtils$1.initialValue(JSONDateUtils.java:31)
  at com.microsoft.appcenter.ingestion.models.json.JSONDateUtils$1.initialValue(JSONDateUtils.java:27)
  at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
  at java.lang.ThreadLocal.get(ThreadLocal.java:170)
  at com.microsoft.appcenter.ingestion.models.json.JSONDateUtils.toString(JSONDateUtils.java:58)
  at com.microsoft.appcenter.ingestion.models.one.CommonSchemaLog.write(CommonSchemaLog.java:298)
  at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.writeLog(DefaultLogSerializer.java:36)
  at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.serializeLog(DefaultLogSerializer.java:58)
  at com.microsoft.appcenter.persistence.DatabasePersistence.putLog(DatabasePersistence.java:254)
  at com.microsoft.appcenter.channel.DefaultChannel.enqueue(DefaultChannel.java:696)
  - locked <0x0a308658> (a com.microsoft.appcenter.channel.DefaultChannel)
  at com.microsoft.appcenter.channel.OneCollectorChannelListener.onPreparedLog(OneCollectorChannelListener.java:160)
  at com.microsoft.appcenter.channel.DefaultChannel.enqueue(DefaultChannel.java:674)
  - locked <0x0a308658> (a com.microsoft.appcenter.channel.DefaultChannel)
  at com.microsoft.appcenter.analytics.Analytics$8.run(Analytics.java:833)
  at com.microsoft.appcenter.AbstractAppCenterService$4.run(AbstractAppCenterService.java:312)
  at com.microsoft.appcenter.AppCenter$7.run(AppCenter.java:757)
  at android.os.Handler.handleCallback(Handler.java:790)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:164)
  at android.os.HandlerThread.run(HandlerThread.java:65)

"Signal Catcher" daemon prio=5 tid=3 Runnable
  | group="system" sCount=0 dsCount=0 flags=0 obj=0x14080098 self=0x74c4224200
  | sysTid=2049 nice=0 cgrp=default sched=0/0 handle=0x74bbb4e4f0
  | state=R schedstat=( 14152240 64764998 20 ) utm=0 stm=1 core=0 HZ=100
  | stack=0x74bba54000-0x74bba56000 stackSize=1005KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 00000000003cfa70  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*)+208)
  native: #01 pc 00000000004a24a0  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+348)
  native: #02 pc 00000000004ba24c  /system/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+860)
  native: #03 pc 00000000004b2a40  /system/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+472)
  native: #04 pc 00000000004b23bc  /system/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+792)
  native: #05 pc 00000000004b1fc0  /system/lib64/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+912)
  native: #06 pc 000000000048688c  /system/lib64/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+196)
  native: #07 pc 00000000004907fc  /system/lib64/libart.so (art::SignalCatcher::HandleSigQuit()+2100)
  native: #08 pc 000000000048f240  /system/lib64/libart.so (art::SignalCatcher::Run(void*)+348)
  native: #09 pc 000000000006a488  /system/lib64/libc.so (__pthread_start(void*)+36)
  native: #10 pc 000000000001f408  /system/lib64/libc.so (__start_thread+68)
  (no managed stack frames)

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7296b168 self=0x74c42c2a00
  | sysTid=2039 nice=0 cgrp=default sched=0/0 handle=0x75490579a8
  | state=S schedstat=( 526337917 1887131361 633 ) utm=41 stm=11 core=1 HZ=100
  | stack=0x7fe4ca3000-0x7fe4ca5000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/2039/stack)
  native: #00 pc 000000000006cb70  /system/lib64/libc.so (__epoll_pwait+8)
  native: #01 pc 000000000001fbbc  /system/lib64/libc.so (epoll_pwait+52)
  native: #02 pc 0000000000015de0  /system/lib64/libutils.so (android::Looper::pollInner(int)+148)
  native: #03 pc 0000000000015cc4  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+108)
  native: #04 pc 0000000000111714  /system/lib64/libandroid_runtime.so (???)
  native: #05 pc 00000000001fcf3c  /system/framework/arm64/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+140)
  at android.os.MessageQueue.nativePollOnce(Native method)
  at android.os.MessageQueue.next(MessageQueue.java:325)
  at android.os.Looper.loop(Looper.java:142)
  at android.app.ActivityThread.main(ActivityThread.java:6518)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by AnastasiaKubova** [comment]
Hi and thanks for getting in touch with us! We already had similar issue and fixed it in [3.2.2](https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.2.2) version of SDK. Could you please update the SDK to the latest version and let me know if this problem persists.

**Comment by yulin-li** [comment]
Thanks, I will upgrade to 3.3.x and try again. Closing it now.
