### ISSUE TITLE
OutOfMemoryError on handling log sending failure

### ISSUE THREAD

**Issue by p-galanin** [microsoft/appcenter-sdk-android#1530]
### **Description**
Deleting logs after sending failure causes`OutOfMemoryError` in case of lots of payload files.

### **Repro Steps**

1. Generate a lot of large (> 2 mb) logs. 
In our project we save native crash minidumps to the minidump folder. Each minidump is about 4 mb.
2. Start AppCenter with Crashes service.
Minidumps are converted and stored in /appcenter/database_large_payloads/groupErrors.
3. Cause unrecoverable log sending failure.
In our project we have just OOM stacktraces, so we don't know the real cause of the failure. During handling of this failure, logs are loaded into memory. In this case `com.microsoft.appcenter.persistence.DatabasePersistence#getLogs` is called with batch size 100, so up to 100 logs with its payload are loaded in memory - this can cause OOM.

```
java.lang.OutOfMemoryError: Failed to allocate a 3211976 byte allocation with 2821808 free bytes and 2MB until OOM, max allowed footprint 268435456, growth limit 268435456
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:220)
        at java.lang.StringBuffer.toString(StringBuffer.java:671)
        at java.io.BufferedReader.readLine(BufferedReader.java:338)
        at java.io.BufferedReader.readLine(BufferedReader.java:400)
        at com.microsoft.appcenter.utils.storage.FileManager.read(FileManager.java:76)
        at com.microsoft.appcenter.persistence.DatabasePersistence.getLogs(DatabasePersistence.java:491)
        at com.microsoft.appcenter.channel.DefaultChannel.deleteLogsOnSuspended(DefaultChannel.java:428)
        at com.microsoft.appcenter.channel.DefaultChannel.suspend(DefaultChannel.java:419)
        at com.microsoft.appcenter.channel.DefaultChannel.handleSendingFailure(DefaultChannel.java:599)
        at com.microsoft.appcenter.channel.DefaultChannel.access$200(DefaultChannel.java:50)
        at com.microsoft.appcenter.channel.DefaultChannel$1$2.run(DefaultChannel.java:532)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### **Details**
SDK version: 4.1.1
OS version: at least 8.0.0, 10, 11
Devices: Galaxy A51, Galaxy A10, Mi A2 Lite and other

**Comment by DmitriyKirakosyan** [comment]
Hi @p-galanin 

Thank you for bringing this issue to our attention!
We will test it and get back to you with an update.

**Comment by AnastasiaKubova** [comment]
Hi, @p-galanin ! I am trying to reproduce this issue but I can't get the same error. Have you a chance to share [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level) with reproducing this issue or sample project with repo steps?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
