### ISSUE TITLE
W/AppCenter: Try #1 failed and will be retried in xxxx ms

### ISSUE THREAD

**Issue by ljunquera** [microsoft/appcenter-sdk-android#1566]
When I run my app in the emulator I always get this error:

```
2021-10-25 22:21:06.948 6917-6917/com.xxx.yyy W/AppCenter: Try #1 failed and will be retried in 9529 ms
    java.net.SocketTimeoutException: SSL handshake timed out
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at d.d.b.n.c.a(:226)
        at d.d.b.n.c.b(:279)
        at d.d.b.n.c.doInBackground(:48)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

I integrated exactly as was outlined in the portal and initiated in the MainActivity:

```
        //APP_CENTER_SECRET
        Log.d(TAG, "MainActivity.onCreate: starting AppCenter...");
        AppCenter.start(getApplication(), BuildConfig.APP_CENTER_SECRET,
                Analytics.class, Crashes.class);
        AppCenter.setLogLevel(Log.VERBOSE);
```

The configuration/device is as follow:

```
2021-10-25 22:21:05.447 6917-7001/com.xxx.yyy V/AppCenter: {
      "logs": [
        {
          "type": "startSession",
          "timestamp": "2021-10-26T02:20:53.808Z",
          "sid": "**************",
          "device": {
            "sdkName": "appcenter.android",
            "sdkVersion": "4.1.0",
            "model": "Android SDK built for x86",
            "oemName": "Google",
            "osName": "Android",
            "osVersion": "10",
            "osBuild": "QSR1.190920.001",
            "osApiLevel": 29,
            "locale": "en_US",
            "timeZoneOffset": -240,
            "screenSize": "1080x2028",
            "appVersion": "1.0.28",
            "carrierName": "Android",
            "carrierCountry": "us",
            "appBuild": "28",
            "appNamespace": "com.xxx.yyy"
          }
        }
      ]
    }
```

**Comment by Wufus** [comment]
Still actual problem for desktop Win32 app based on WinUI3:
`2023-08-31 11:34:29.072 [AppCenter] WARN: Try #1 failed and will be retried in 9085 ms`
|Package| Version|
|-|-|
|Microsoft.AppCenter.Analytics|5.0.2|
|Microsoft.AppCenter.Crashes|5.0.2|
|Microsoft.WindowsAppSDK|1.4.230822000|
|Microsoft.Windows.SDK.BuildTools|10.0.22621.756|

Internet connection is excellent and I can see events in AppCenter

**Comment by DmitriyKirakosyan** [comment]
Hi @Wufus,

I'm currently in discussion with the backend team regarding this matter. In the meantime, could you please confirm if you're still encountering this issue consistently every time?

**Comment by Wufus** [comment]
Hi @DmitriyKirakosyan 

I have run my application several times and sometimes I get these messages. But one day I got 3 messages:
```
2023-09-01 17:19:25.964 [AppCenter] WARN: Try #1 failed and will be retried in 5090 ms
2023-09-01 17:19:25.966 [AppCenter] WARN: Try #1 failed and will be retried in 5090 ms
2023-09-01 17:19:37.180 [AppCenter] WARN: Try #2 failed and will be retried in 21889 ms
```

P.S. I just now saw that it's a "appcenter-sdk-android" repo

**Comment by pasha-o** [comment]
I can also confirm the issue exists on xamarin.forms android real device :
[AppCenter] Try #1 failed and will be retried in 9147 ms
[AppCenter] java.net.SocketTimeoutException: failed to connect to in.appcenter.ms/52.232.209.85 (port 443) from /10.0.0.4 (port 42760) after 10000ms
[AppCenter] 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
[AppCenter] 	at libcore.io.IoBridge.connect(IoBridge.java:179)
[AppCenter] 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
[AppCenter] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
[AppCenter] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
[AppCenter] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
[AppCenter] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
[AppCenter] 	at java.net.Socket.connect(Socket.java:646)
[AppCenter] 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
[AppCenter] 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
[AppCenter] 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
[AppCenter] 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
[AppCenter] 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[AppCenter] 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[AppCenter] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
[AppCenter] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
[AppCenter] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
[AppCenter] 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
[AppCenter] 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
[AppCenter] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
[AppCenter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
[AppCenter] 	at java.lang.Thread.run(Thread.java:1012)

**Comment by DmitriyKirakosyan** [comment]
@Wufus, @pasha-o, could you please share additional details about your projects? If possible, consider providing a minimal demo application that replicates the issue you're encountering.

Is this issue currently causing significant obstacles for your work? Do the events eventually reach the App Center after multiple retry attempts, or is the SDK failing to send events entirely due to this problem?

**Comment by OleksandrTGriiip** [comment]
@DmitriyKirakosyan , it happens not every run but frequently. And when it happens nothing reach the App Center neither analytics nor errors.

**Comment by dgyesbreghs** [comment]
@DmitriyKirakosyan @OleksandrTGriiip we're also getting the same error message.
Is there any update on this issue?

**Comment by DmitriyKirakosyan** [comment]
@dgyesbreghs @OleksandrTGriiip, it seems unlikely that this is an SDK issue.
@dgyesbreghs, can you specify when this issue first started occurring?

**Comment by dgyesbreghs** [comment]
@DmitriyKirakosyan we noticed it a couple of weeks ago.

**Comment by DmitriyKirakosyan** [comment]
@dgyesbreghs, there haven't been any changes to the SDK in the past month that could potentially cause the issue you're experiencing. I suggest reaching out to our [support team](https://learn.microsoft.com/en-us/appcenter/help) for assistance; they'll be able to help you with this matter.
