### ISSUE TITLE
NullPointerException on Distribute.resumeDistributeWorkflow

### ISSUE THREAD

**Issue by vjgarciag96** [microsoft/appcenter-sdk-android#1656]
### **Description**

We are experiencing the next crash in our app, which seems to come from the distribute SDK:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:190)
        at android.view.ContextThemeWrapper.getTheme(ContextThemeWrapper.java:174)
        at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:227)
        at android.app.AlertDialog$Builder.<init>(AlertDialog.java:478)
        at com.microsoft.appcenter.distribute.Distribute.showUpdateSetupFailedDialog(Distribute.java:1581)
        at com.microsoft.appcenter.distribute.Distribute.resumeDistributeWorkflow(Distribute.java:874)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### **Repro Steps**
Unfortunately, we don't have any consistent repro steps. We have one user that somehow has got into a state in which they always run into the crash every time they open the app.

Some things that may be relevant:

1. The user was using an AppCenter-provided version of the app.
2. At some point they switched to use a sideloaded version of the app.
3. They have the app installed in a personal and a work profile.

### **Details**

1. Which SDK version are you using?
    We were using 3.3.0 the first time we reproduced the issue, but updated to 4.4.5 and we are still experiencing the it.
2. Which OS version did you experience the issue on?
    Android 12
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    Galaxy S21 Ultra 5G
5. What third party libraries are you using?
    A bunch of them, not sure if an exhaustive list would be helpful here as there are more than 200. Any specific libraries that you would be interested to know about?
6. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

I could get this from the user experiencing the problem, not sure how helpful it is.
```
2022-10-19 12:10:40.874 28627-28750/? V/AppCenter: {"logs":[{"type":"managedError","timestamp":"2022-10-17T05:01:02.029Z","userId":"4dd7d5dc-ddb4-4e19-98d0-baff645f4910","device":{"sdkName":"appcenter.android","sdkVersion":"3.3.0","model":"SM-G998B","oemName":"samsung","osName":"Android","osVersion":"12","osBuild":"SP1A.210812.016","osApiLevel":31,"locale":"en_GB","timeZoneOffset":60,"screenSize":"1080x2190","appVersion":"8.10.26.100","carrierName":"EE","carrierCountry":"gb","appBuild":"1096418880","appNamespace":"com.touchtype.swiftkey.cesar"},"id":"bafd48ab-bd64-4084-ab2e-7c19924dc1b7","processId":31849,"processName":"com.touchtype.swiftkey.cesar","errorThreadId":2,"errorThreadName":"main","fatal":true,"appLaunchTimestamp":"2022-10-17T05:01:01.760Z","architecture":"arm64-v8a","exception":{"type":"java.lang.NullPointerException","message":"Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference","frames":[{"className":"android.content.ContextWrapper","methodName":"getApplicationInfo","lineNumber":190,"fileName":"ContextWrapper.java"},{"className":"android.view.ContextThemeWrapper","methodName":"getTheme","lineNumber":174,"fileName":"ContextThemeWrapper.java"},{"className":"android.app.AlertDialog","methodName":"resolveDialogTheme","lineNumber":227,"fileName":"AlertDialog.java"},{"className":"android.app.AlertDialog$Builder","methodName":"<init>","lineNumber":478,"fileName":"AlertDialog.java"},{"className":"com.microsoft.appcenter.distribute.Distribute","methodName":"L","lineNumber":15},{"className":"com.microsoft.appcenter.distribute.Distribute","methodName":"C","lineNumber":300,"fileName":"SourceFile"},{"className":"ha.c","methodName":"run","lineNumber":2},{"className":"android.os.Handler","methodName":"handleCallback","lineNumber":938,"fileName":"Handler.java"},{"className":"android.os.Handler","methodName":"dispatchMessage","lineNumber":99,"fileName":"Handler.java"},{"className":"android.os.Looper","methodName":"loopOnce","lineNumber":226,"fileName":"Looper.java"},{"className":"android.os.Looper","methodName":"loop","lineNumber":313,"fileName":"Looper.java"},{"className":"android.app.ActivityThread","methodName":"main","lineNumber":8751,"fileName":"ActivityThread.java"},{"className":"java.lang.reflect.Method","methodName":"invoke","lineNumber":-2,"fileName":"Method.java"},{"className":"com.android.internal.os.RuntimeInit$MethodAndArgsCaller","methodName":"run","lineNumber":571,"fileName":"RuntimeInit.java"},{"className":"com.android.internal.os.ZygoteInit","methodName":"main","lineNumber":1135,"fileName":"ZygoteInit.java"}]},"threads":[{"id":55827,"name":"ThemeManager","frames":[{"className":"android.os.BinderProxy","methodName":"transactNative","lineNumber":-2,"fileName":"BinderProxy.java"},{"className":"android.os.BinderProxy","methodName":"transact","lineNumber":635,"fileName":"BinderProxy.java"},{"className":"android.app.job.IJobScheduler$Stub$Proxy","methodName":"enqueue","lineNumber":342,"fileName":"IJobScheduler.java"},{"className":"android.app.JobSchedulerImpl","methodName":"enqueue","lineNumber":56,"fileName":"JobSchedulerImpl.java"},{"className":"androidx.core.app.JobIntentService$g","methodName":"a","lineNumber":9},{"className":"androidx.core.app.JobIntentService","methodName":"b","lineNumber":16},{"className":"com.touchtype.telemetry.TelemetryJobIntentService","methodName":"h","lineNumber":93,"fileName":"SourceFile"},{"className":"ok.a","methodName":"y","lineNumber":17},{"className":"dh.l$b","methodName":"onSuccess","lineNumber":33,"fileName":"SourceFile"},{"className":"com.google.common.util.concurrent.Futures$CallbackListener","methodName":"run","lineNumber":28},{"className":"java.util.concurrent.ThreadPoolExecutor","methodName":"runWorker","lineNumber":1137,"fileName":"ThreadPoolExecutor.java"},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","methodName":"run","lineNumber":637,"fileName":"ThreadPoolExecutor.java"},{"className":"java.lang.Thread","methodName":"run","lineNumber":1012,"fileName":"Thread.java"}]},{"id"
2022-10-19 12:10:40.893 28627-28753/? V/AppCenter: {"logs":[{"type":"managedError","timestamp":"2022-10-17T06:16:32.880Z","userId":"4dd7d5dc-ddb4-4e19-98d0-baff645f4910","device":{"sdkName":"appcenter.android","sdkVersion":"3.3.0","model":"SM-G998B","oemName":"samsung","osName":"Android","osVersion":"12","osBuild":"SP1A.210812.016","osApiLevel":31,"locale":"en_GB","timeZoneOffset":60,"screenSize":"1080x2190","appVersion":"8.10.26.100","carrierName":"EE","carrierCountry":"gb","appBuild":"1096418880","appNamespace":"com.touchtype.swiftkey.cesar"},"id":"80850514-a16d-4aea-a219-3976200edcc4","processId":21935,"processName":"com.touchtype.swiftkey.cesar","errorThreadId":2,"errorThreadName":"main","fatal":true,"appLaunchTimestamp":"2022-10-17T06:16:32.750Z","architecture":"arm64-v8a","exception":{"type":"java.lang.NullPointerException","message":"Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference","frames":[{"className":"android.content.ContextWrapper","methodName":"getApplicationInfo","lineNumber":190,"fileName":"ContextWrapper.java"},{"className":"android.view.ContextThemeWrapper","methodName":"getTheme","lineNumber":174,"fileName":"ContextThemeWrapper.java"},{"className":"android.app.AlertDialog","methodName":"resolveDialogTheme","lineNumber":227,"fileName":"AlertDialog.java"},{"className":"android.app.AlertDialog$Builder","methodName":"<init>","lineNumber":478,"fileName":"AlertDialog.java"},{"className":"com.microsoft.appcenter.distribute.Distribute","methodName":"L","lineNumber":15},{"className":"com.microsoft.appcenter.distribute.Distribute","methodName":"C","lineNumber":300,"fileName":"SourceFile"},{"className":"ha.c","methodName":"run","lineNumber":2},{"className":"android.os.Handler","methodName":"handleCallback","lineNumber":938,"fileName":"Handler.java"},{"className":"android.os.Handler","methodName":"dispatchMessage","lineNumber":99,"fileName":"Handler.java"},{"className":"android.os.Looper","methodName":"loopOnce","lineNumber":226,"fileName":"Looper.java"},{"className":"android.os.Looper","methodName":"loop","lineNumber":313,"fileName":"Looper.java"},{"className":"android.app.ActivityThread","methodName":"main","lineNumber":8751,"fileName":"ActivityThread.java"},{"className":"java.lang.reflect.Method","methodName":"invoke","lineNumber":-2,"fileName":"Method.java"},{"className":"com.android.internal.os.RuntimeInit$MethodAndArgsCaller","methodName":"run","lineNumber":571,"fileName":"RuntimeInit.java"},{"className":"com.android.internal.os.ZygoteInit","methodName":"main","lineNumber":1135,"fileName":"ZygoteInit.java"}]},"threads":[{"id":56035,"name":"AppCenter.Looper","frames":[{"className":"android.os.MessageQueue","methodName":"nativePollOnce","lineNumber":-2,"fileName":"MessageQueue.java"},{"className":"android.os.MessageQueue","methodName":"next","lineNumber":335,"fileName":"MessageQueue.java"},{"className":"android.os.Looper","methodName":"loopOnce","lineNumber":186,"fileName":"Looper.java"},{"className":"android.os.Looper","methodName":"loop","lineNumber":313,"fileName":"Looper.java"},{"className":"android.os.HandlerThread","methodName":"run","lineNumber":67,"fileName":"HandlerThread.java"}]},{"id":56054,"name":"OkHttp ConnectionPool","frames":[{"className":"java.lang.Object","methodName":"wait","lineNumber":-2,"fileName":"Object.java"},{"className":"com.android.okhttp.ConnectionPool$1","methodName":"run","lineNumber":106,"fileName":"ConnectionPool.java"},{"className":"java.util.concurrent.ThreadPoolExecutor","methodName":"runWorker","lineNumber":1137,"fileName":"ThreadPoolExecutor.java"},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","methodName":"run","lineNumber":637,"fileName":"ThreadPoolExecutor.java"},{"className":"java.lang.Thread","methodName":"run","lineNumber":1012,"fileName":"Thread.java"}]},{"id":56019,"name":"HeapTaskDaemon","frames":[]},{"id":56051,"name":"AsyncTask #2","frames":[{"className":"java.net.SocketInputStream","methodName":"socketRead0","lineNumber":-2,"fileName":"SocketInputStream.java"},{"cl
2022-10-19 12:10:41.511 28627-28627/? E/AndroidRuntime: FATAL EXCEPTION: main    Process: com.touchtype.swiftkey.cesar, PID: 28627    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference        at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:190)        at android.view.ContextThemeWrapper.getTheme(ContextThemeWrapper.java:174)        at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:227)        at android.app.AlertDialog$Builder.<init>(AlertDialog.java:478)        at com.microsoft.appcenter.distribute.Distribute.R(s:4)        at com.microsoft.appcenter.distribute.Distribute.H(s:74)        at v02.run(s:20)        at android.os.Handler.handleCallback(Handler.java:938)        at android.os.Handler.dispatchMessage(Handler.java:99)        at android.os.Looper.loopOnce(Looper.java:226)        at android.os.Looper.loop(Looper.java:313)        at android.app.ActivityThread.main(ActivityThread.java:8751)        at java.lang.reflect.Method.invoke(Native Method)        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-10-19 12:10:41.542 28627-28627/? D/AppCenterCrashes: Saved JSON content
```

**Comment by vjgarciag96** [comment]
By digging into the code the problem seems to be that `mForegroundActivity` is null at this point: https://github.com/microsoft/appcenter-sdk-android/blob/82e68bb7764c0607ca2def51874965116123dff1/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L1584

There's a check for `mForegroundActivity != null` in `resumeDistributeWorkflow` (which seems to be the only method calling `showUpdateSetupFailedDialog`), so I'm not sure how that code path is reached with a null `Activity`. I can think only of some memory visibility problem, or the `Activity` becoming null somehow after the check.

I guess it could be fixed by adding another `mForegroundActivity != null` check within that function but it would be nice to find the root cause of the problem first.

Just sharing that in case it is helpful!

**Comment by DmitriyKirakosyan** [comment]
Hi @vjgarciag96 , thank you for this report and the details! I'm marking it as a bug.
May I ask you to send more logs? from the app start til the crash happens?

**Comment by vjgarciag96** [comment]
> Hi @vjgarciag96 , thank you for this report and the details! I'm marking it as a bug.
May I ask you to send more logs? from the app start til the crash happens?

@tehmur can you please help providing the requested logs?

**Comment by DmitriyKirakosyan** [comment]
Turn on verbose logging (`AppCenter.setLogLevel(Log.VERBOSE)`) before `AppCenter.Start`. Run the app and find the app logs tracing in the Android Studio's logcat. I would like to see more AppCenter related logs before the app crashes.

**Comment by shadyabarada** [comment]
Hi @vjgarciag96 , alongside the requested logs (after you produce them),  would it be possible to try clearing app cache and data from the device settings and trying to open the app again and share with us if the issue continuous?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this bug in the next year, I'm closing the issue.
