### ISSUE TITLE
Distribute in-app update issue

### ISSUE THREAD

**Issue by aherman** [microsoft/appcenter-sdk-android#1687]
### **Description**

I am trying to set Distribute in-app updates, I did all the steps in the documentation, but I don't get an update dialog in any way. Down there I copied Distribute logcat output when the app is launched. MinSdk is set to 31.

### **Repro Steps**

1. Launch the app with the specs stated below
2. See logs

### **Details**

1. Which SDK version are you using? 5.0.1
3. Which OS version did you experience the issue on? Android 13
4. What device version did you see this error on?  Were you using an emulator or a physical device? Google Pixel 5a
5. What third party libraries are you using? n/a
6. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

``` D  Resetting workflow on entering foreground.
  D  InstallerPackageName=com.google.android.packageinstaller
  D  Resume distribute workflow...
  I  Get latest release details...
  D  Check if we need to report release installation..
  D  Current release was already reported, skip reporting.
  V  Calling https://api.appcenter.ms/v0.1/public/sdk/apps/****************************a0429045/releases/latest?release_hash=5b62c99300c9b4a5d6c3962ee549ea0f34a5307b733cc6fda5f1c36e88fa97ec...
  V  Headers: {}
  D  Resume distribute workflow...
  V  Already checking or checked latest release.
  D  Complete current updating process.
  E  Failed to check latest release
     org.json.JSONException: No value for android_min_api_level
     	at org.json.JSONObject.get(JSONObject.java:398)
     	at org.json.JSONObject.getInt(JSONObject.java:487)
     	at com.microsoft.appcenter.distribute.i.l(Unknown Source:81)
     	at com.microsoft.appcenter.distribute.Distribute$e.b(Unknown Source:8)
     	at g5.e.b(Unknown Source:2)
     	at g5.e.b(Unknown Source:2)
     	at g5.c.onPostExecute(Unknown Source:21)
     	at android.os.AsyncTask.finish(AsyncTask.java:771)
     	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
     	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
     	at android.os.Handler.dispatchMessage(Handler.java:106)
     	at android.os.Looper.loopOnce(Looper.java:201)
     	at android.os.Looper.loop(Looper.java:288)
     	at android.app.ActivityThread.main(ActivityThread.java:7884)
        at java.lang.reflect.Method.invoke(Native Method)
     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)```

**Comment by MikhailSuendukov** [comment]
Hi @aherman  and thank you for reaching out to us. The problem is that for some reason you are missing the `android_min_api_level` parameter in the update file or in your current application. Please make sure this parameter is specified.

**Comment by aherman** [comment]
@MikhailSuendukov Unfortunately, it has been specified, but it seems like it cannot be recognized. Is there a workaround for this issue?

**Comment by MikhailSuendukov** [comment]
Sorry for the long wait. Since this error is not reproduced on a simple Android application, it would be very useful for localizing the error to have the simplest demo application on which this error would be reproduced.

**Comment by AnatolyPristensky** [comment]
Hello, we haven't heard from you for a while, so I'm closing this issue. 
Please feel free to reopen it in case of new information.
