### ISSUE TITLE
get hostAddress on background

### ISSUE THREAD

**Issue by ling9400** [microsoft/appcenter-sdk-android#1724]
### **Description**

get hostAddress on background

### **Repro Steps**

at java.net.Inet4Address.getHostAddress()
	at java.net.InetAddress.toString(InetAddress.java:659)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at libcore.io.IoBridge.connectDetail(IoBridge.java:207)
	at libcore.io.IoBridge.isConnected(IoBridge.java:269)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:188)
	at libcore.io.IoBridge.connect(IoBridge.java:130)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
	at java.net.Socket.connect(Socket.java:616)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
	at c.y.a.d.e.a(DefaultHttpClientCallTask.java:37)
	at c.y.a.d.e.a(DefaultHttpClientCallTask.java:60)
	at c.y.a.d.e.doInBackground(DefaultHttpClientCallTask.java:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

### **Details**

1. Which SDK version are you using?
    - e.g. 4.4.3 or 5.0.3

**Comment by AnatolyPristensky** [comment]
Hello @ling9400, could you please describe your issue more detailed?
It would be very helpful for us if you can fill the following form:




### **Description**

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - e.g. Android 8.1.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 2 emulator, Samsung Galaxy S8 physical device
4. What third party libraries are you using?
    - example
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

**Comment by ling9400** [comment]
> Hello @ling9400, could you please describe your issue more detailed? It would be very helpful for us if you can fill the following form:
> 
> ### **Description**
> Please describe the issue you are facing using the SDK.
> 
> ### **Repro Steps**
> Please list the steps used to reproduce your issue.
> 
> 
> ### **Details**
> 1. Which SDK version are you using?
>    
>    * e.g. 1.5.0
> 2. Which OS version did you experience the issue on?
>    
>    * e.g. Android 8.1.0
> 3. What device version did you see this error on?  Were you using an emulator or a physical device?
>    
>    * e.g. Google Pixel 2 emulator, Samsung Galaxy S8 physical device
> 4. What third party libraries are you using?
>    
>    * example
> 5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:
Description
the sdk getHostAddress when app on background

Repro Steps
1.init sdk
2.put app on background

Details
Which SDK version are you using?
e.g. 4.4.3 and 5.0.3
Which OS version did you experience the issue on?
all vivo device  
What device version did you see this error on? Were you using an emulator or a physical device?
all vivo device 
What third party libraries are you using?
appcenter android sdk
Please enable verbose logging for your app using AppCenter.setLogLevel(Log.VERBOSE) before your call to AppCenter.start(...) and include the logs here:  
at java.net.Inet4Address.getHostAddress()
at java.net.InetAddress.toString(InetAddress.java:659)
at java.lang.String.valueOf(String.java:2827)
at java.lang.StringBuilder.append(StringBuilder.java:132)
at libcore.io.IoBridge.connectDetail(IoBridge.java:207)
at libcore.io.IoBridge.isConnected(IoBridge.java:269)
at libcore.io.IoBridge.connectErrno(IoBridge.java:188)
at libcore.io.IoBridge.connect(IoBridge.java:130)
at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
at java.net.Socket.connect(Socket.java:616)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
at c.y.a.d.e.a(DefaultHttpClientCallTask.java:37)
at c.y.a.d.e.a(DefaultHttpClientCallTask.java:60)
at c.y.a.d.e.doInBackground(DefaultHttpClientCallTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by MikhailSuendukov** [comment]
Hello, the error itself is missing in your logs, and there is also no mention of the support center in the stack trace. Are you sure the problem is with the appcenter sdk?

**Comment by ling9400** [comment]
> Hello, the error itself is missing in your logs, and there is also no mention of the appcenter center in the stack trace. Are you sure the problem is with the appcenter sdk?

Yes,i'm sure,DefaultHttpClientCallTask is the class in appcenter sdk and it is the only class in my code

**Comment by MikhailSuendukov** [comment]
Yes, indeed, but without information about what kind of error and under what conditions it occurs, it is impossible to continue investigating it. So could you please provide the full stack trace along with the error and describe how this error can be reproduced.

**Comment by ling9400** [comment]
> Yes, indeed, but without information about what kind of error and under what conditions it occurs, it is impossible to continue investigating it. So could you please provide the full stack trace along with the error and describe how this error can be reproduced.

it is not a bug, it just a Privacy issues in Chinese,is there any api to close get hostAddress？

**Comment by MikhailSuendukov** [comment]
I'm sorry, but I don't quite understand what API you require?

**Comment by ling9400** [comment]
> I'm sorry, but I don't quite understand what API you require?

at java.net.Inet4Address.getHostAddress()
	at java.net.InetAddress.toString(InetAddress.java:659)
	at java.lang.String.valueOf(String.java:2827)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at libcore.io.IoBridge.connectDetail(IoBridge.java:207)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
	at libcore.io.IoBridge.connect(IoBridge.java:130)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
	at java.net.Socket.connect(Socket.java:616)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

is this logs can help you?

**Comment by MikhailSuendukov** [comment]
I am currently closing this issue due to inactivity, but if you have additional information or new questions, feel free to reopen it.
