### ISSUE TITLE
Distribute API checks do not work on devices supporting only old/weak TLS 1.2 ciphers

### ISSUE THREAD

**Issue by phdonnelly** [Microsoft/AppCenter-SDK-Android#935]
### **Description**

Appcenter update functionality fails on older Motorola/Symbol/Zebra devices (specifically MC32, MC67, and MC92 that I've tested). This appears to be very similar to issue #917 that has been fixed for the analytics module but is still affecting the distribute module.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Use appcenter Distribute model on a Xamarin client on one of the above devices.
2. All https calls to "https://api.appcenter.ms/" will fail due to SSL errors, and update functionality will not work.

### **Details**

1. Which SDK version are you using?
    - 1.13.0 (DotNetClient, Xamarin) 1.11.2 (Android)
2. Which OS version did you experience the issue on?
    - Android 4.1 Jelly Bean (API 16)
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Zebra/Symbol MC32, MC92, MC67
4. What third party libraries are you using?
    - repeatable without any 3rd part libraries.
5. Please enable verbose logging for your app using `AppCenter.setLogLevel(Log.VERBOSE)` before your call to `AppCenter.start(...)` and include the logs here:

Relevant log snippet:

```
D/AppCenter( 5829): Storing a log to the Persistence database for log type event with flags=1
D/AppCenter( 5829): Stored a log to the Persistence database for log type event with databaseId=62
D/AppCenter( 5829): enqueue(group_analytics) pendingLogCount=2
D/AppCenter( 5829): checkPendingLogs(group_analytics) pendingLogCount=2
D/dalvikvm( 5829): GC_CONCURRENT freed 180K, 3% free 11234K/11527K, paused 13ms+3ms, total 44ms
D/AppCenter( 5829): checkPendingLogs(group_analytics) pendingLogCount=2
D/AppCenter( 5829): checkPendingLogs(group_core) pendingLogCount=0
V/AppCenter( 5829): Calling https://in.appcenter.ms/logs?api-version=1.0.0...
V/AppCenter( 5829): Headers: {Install-ID=9a786df4-2bdb-4d28-a30d-76abb66d06fc, Content-Type=application/json, App-Secret=****************************c4ca7ade}
V/AppCenter( 5829): {
.. snipped event data ...
V/AppCenter( 5829): }
V/AppCenterDistribute( 5829): Calling https://api.appcenter.ms/v0.1/sdk/apps/****************************c4ca7ade/releases/latest?release_hash=523bcb2dcf962e47ee818ddadd7d11d0a20ffb202bd568a5e330b823c2ad8c37...
V/AppCenterDistribute( 5829): Headers: {x-api-token=********************************8498b5c4}
V/AppCenter( 5829): Calling https://in.appcenter.ms/logs?api-version=1.0.0...
V/AppCenter( 5829): Headers: {Install-ID=9a786df4-2bdb-4d28-a30d-76abb66d06fc, Content-Type=application/json, App-Secret=****************************c4ca7ade}
V/AppCenter( 5829): {
V/AppCenter( 5829):   "logs": [
V/AppCenter( 5829):     {
V/AppCenter( 5829):       "device": {
V/AppCenter( 5829):         "screenSize": "480x640",
V/AppCenter( 5829):         "model": "MC67NA",
V/AppCenter( 5829):         "osVersion": "4.1.1",
V/AppCenter( 5829):         "timeZoneOffset": -300,
V/AppCenter( 5829):         "appBuild": "209999",
V/AppCenter( 5829):         "locale": "en_US",
V/AppCenter( 5829):         "sdkVersion": "1.11.2",
V/AppCenter( 5829):         "oemName": "Motorola Solutions",
V/AppCenter( 5829):         "wrapperSdkVersion": "1.13.0",
V/AppCenter( 5829):         "appVersion": "2.0.9999",
V/AppCenter( 5829):         "appNamespace": "com.porky.sap_access_porky",
V/AppCenter( 5829):         "wrapperSdkName": "appcenter.xamarin",
V/AppCenter( 5829):         "osApiLevel": 16,
V/AppCenter( 5829):         "osName": "Android",
V/AppCenter( 5829):         "sdkName": "appcenter.android",
V/AppCenter( 5829):         "osBuild": "01-4AJ11-J-2200-0001-00-M1-030515",
V/AppCenter( 5829):         "wrapperRuntimeVersion": "9.1.5.1"
V/AppCenter( 5829):       },
V/AppCenter( 5829):       "timestamp": "2019-01-24T20:34:41.129Z",
V/AppCenter( 5829):       "sid": "e8d363d0-5a74-40d5-8539-7bae26667ffb",
V/AppCenter( 5829):       "distributionGroupId": "137835ed-fd47-49ce-8ac4-5b9837707948",
V/AppCenter( 5829):       "properties": [
V/AppCenter( 5829):         {
V/AppCenter( 5829):           "value": "*******",
V/AppCenter( 5829):           "type": "string",
V/AppCenter( 5829):           "name": "username"
V/AppCenter( 5829):         }
V/AppCenter( 5829):       ],
V/AppCenter( 5829):       "type": "customProperties"
V/AppCenter( 5829):     }
V/AppCenter( 5829):   ]
V/AppCenter( 5829): }
W/AppCenter( 5829): Try #2 failed and will be retried in 234625 ms
W/AppCenter( 5829): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x525f9378: Failure in SSL library, usually a protocol error
W/AppCenter( 5829): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x48c947de:0x00000000)
W/AppCenter( 5829): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:436)
W/AppCenter( 5829): 	at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
W/AppCenter( 5829): 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:478)
W/AppCenter( 5829): 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
W/AppCenter( 5829): 	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:289)
W/AppCenter( 5829): 	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:239)
W/AppCenter( 5829): 	at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
W/AppCenter( 5829): 	at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:486)
W/AppCenter( 5829): 	at libcore.net.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:134)
W/AppCenter( 5829): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:271)
W/AppCenter( 5829): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:304)
W/AppCenter( 5829): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:39)
W/AppCenter( 5829): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/AppCenter( 5829): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/AppCenter( 5829): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/AppCenter( 5829): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
W/AppCenter( 5829): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/AppCenter( 5829): 	at java.lang.Thread.run(Thread.java:856)
W/AppCenter( 5829): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x525f9378: Failure in SSL library, usually a protocol error
W/AppCenter( 5829): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x48c947de:0x00000000)
W/AppCenter( 5829): 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
W/AppCenter( 5829): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:395)
W/AppCenter( 5829): 	... 17 more
V/AppCenter( 5829): HTTP response status=200 payload=CorrelationId: 58c26ae9-f8fb-4759-88e6-c549caa7fcd4  ReasonCode: Success
D/AppCenter( 5829): Deleting logs from the Persistence database for group_core with ceeddd9b-e5bd-40fb-97df-8a128d6efffb
D/AppCenter( 5829): The IDs for deleting log(s) is/are:
D/AppCenter( 5829): 	60
V/AppCenter( 5829): HTTP response status=200 payload=CorrelationId: 174fc13a-1a82-4282-8b10-face2850794f  ReasonCode: Success
D/AppCenter( 5829): checkPendingLogs(group_core) pendingLogCount=0
D/AppCenter( 5829): Deleting logs from the Persistence database for group_analytics with 7924e7b9-7cec-46d8-95aa-6ba1e3b85f15
D/AppCenter( 5829): The IDs for deleting log(s) is/are:
D/AppCenter( 5829): 	59
D/AppCenter( 5829): checkPendingLogs(group_analytics) pendingLogCount=2
```

The logs are interleaved, but the calls to in.appcenter.ms are succeeding, and the calls to api.appcenter.ms are not.

**Comment by guperrot** [comment]
This is a server side issue where the API gateway used for in-app updates does not have the same level of support for ciphers that logging endpoint does.

We are trying to contact the team in charge of that endpoint.

**Comment by guperrot** [comment]
Can you please run:

```
SSLSocketFactory socketFactory = null;
        try {
            SSLContext sc = SSLContext.getInstance("TLSv1.2");
            sc.init(null, null, null);
            socketFactory = sc.getSocketFactory();
        } catch (KeyManagementException | NoSuchAlgorithmException ignored) {
        }
        SSLSocketFactory delegate = socketFactory != null ? socketFactory : getDefaultSSLSocketFactory();
        SSLSocket sslSocket = null;
        try {
            sslSocket = (SSLSocket) delegate.createSocket();
            sslSocket.setEnabledProtocols(new String[]{"TLSv1.2"});
            Log.v("tmp", "Enabled ciphers:");
            for (String cipher : sslSocket.getEnabledCipherSuites()) {
                Log.v("tmp", cipher);
            }
            Log.v("tmp", "Supported ciphers:");
            for (String cipher : sslSocket.getSupportedCipherSuites()) {
                Log.v("tmp", cipher);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
```

Anywhere in any app for these devices and share what the output of this test code is?
It should match what is documented in https://developer.android.com/reference/javax/net/ssl/SSLSocket but want to make sure, this manufacturer does not deviate from the official firmwares.

Thanks in advance.

**Comment by phdonnelly** [comment]
Sorry for the delay; I accidentally turned off notifications for this ticket; here is the output:

```
V/tmp: Manufacturer: Motorola Solutions
V/tmp: Model: MC67NA
V/tmp: Brand: Android
V/tmp: API level: 16
V/tmp: Enabled ciphers:
V/tmp: SSL_RSA_WITH_RC4_128_MD5
V/tmp: SSL_RSA_WITH_RC4_128_SHA
V/tmp: TLS_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDH_RSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDHE_RSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_DHE_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_DHE_DSS_WITH_AES_128_CBC_SHA
V/tmp: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
V/tmp: SSL_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_RSA_WITH_DES_CBC_SHA
V/tmp: SSL_DHE_RSA_WITH_DES_CBC_SHA
V/tmp: SSL_DHE_DSS_WITH_DES_CBC_SHA
V/tmp: SSL_RSA_EXPORT_WITH_RC4_40_MD5
V/tmp: SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
V/tmp: SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
V/tmp: SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
V/tmp: TLS_EMPTY_RENEGOTIATION_INFO_SCSV
V/tmp: Supported ciphers:
V/tmp: SSL_RSA_WITH_RC4_128_MD5
V/tmp: SSL_RSA_WITH_RC4_128_SHA
V/tmp: TLS_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDH_RSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDHE_RSA_WITH_RC4_128_SHA
V/tmp: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_DHE_RSA_WITH_AES_128_CBC_SHA
V/tmp: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
V/tmp: TLS_DHE_DSS_WITH_AES_128_CBC_SHA
V/tmp: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
V/tmp: SSL_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
V/tmp: TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_RSA_WITH_DES_CBC_SHA
V/tmp: SSL_DHE_RSA_WITH_DES_CBC_SHA
V/tmp: SSL_DHE_DSS_WITH_DES_CBC_SHA
V/tmp: SSL_RSA_EXPORT_WITH_RC4_40_MD5
V/tmp: SSL_RSA_EXPORT_WITH_DES40_CBC_SHA
V/tmp: SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA
V/tmp: SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA
V/tmp: SSL_RSA_WITH_NULL_MD5
V/tmp: SSL_RSA_WITH_NULL_SHA
V/tmp: TLS_ECDH_ECDSA_WITH_NULL_SHA
V/tmp: TLS_ECDH_RSA_WITH_NULL_SHA
V/tmp: TLS_ECDHE_ECDSA_WITH_NULL_SHA
V/tmp: TLS_ECDHE_RSA_WITH_NULL_SHA
V/tmp: SSL_DH_anon_WITH_RC4_128_MD5
V/tmp: TLS_DH_anon_WITH_AES_128_CBC_SHA
V/tmp: TLS_DH_anon_WITH_AES_256_CBC_SHA
V/tmp: SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_DH_anon_WITH_DES_CBC_SHA
V/tmp: TLS_ECDH_anon_WITH_RC4_128_SHA
V/tmp: TLS_ECDH_anon_WITH_AES_128_CBC_SHA
V/tmp: TLS_ECDH_anon_WITH_AES_256_CBC_SHA
V/tmp: TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA
V/tmp: SSL_DH_anon_EXPORT_WITH_RC4_40_MD5
V/tmp: SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA
V/tmp: TLS_ECDH_anon_WITH_NULL_SHA
V/tmp: TLS_EMPTY_RENEGOTIATION_INFO_SCSV
```

**Comment by guperrot** [comment]
Thanks for your reply. None of them are indeed supported by the API endpoint, I am still waiting feedback from the security team to see if we can allow one of those.

**Comment by guperrot** [comment]
We eventually got approval to add 1 of those ciphers and we could test with an Android 4.1 device of our own, the issue is now fixed server side.
